a = "MushfikaJahan"
# b = a[0:8:4]
c = a.lower()
d = a.upper()
e = a.replace("M", "m")
f = a.split("J")
g = a.strip("M")
h = a.find("J")
i = a.isalpha()
j = a.isdigit()
h = a.capitalize()
k = a.title()
print("c is:", c)
print("d is:", d)
print("e is:", e)
print("f is:", f)
print("g is:", g)
print("h is:", h)
print("i is:", i)
print("j is:", j)
print("k is:", k)